### ISSUE TITLE
properly enable (enforce) https on homepage

### ISSUE THREAD

**Issue by ghost** [ifedapoolarewaju/nojs#5]
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https

atm ssl-cert of [`https://nojs.io`](https://nojs.io) only covers `*.github.com` (since it was before `github.io` and enabling https for custom domains), but enforcing it in the repo settings should properly provide one for custom domain.

**Comment by ifedapoolarewaju** [comment]
closing this as we've now reverted from the custom domain `nojs.io` to `github.io`
